sudo: required
services:
    - docker

before_install:
    - docker build -t singhabhinav/react-project -f Dockerfile_dev .

script:
    - docker run -e CI=true singhabhinav/react-project npm run test

deploy:
    provider: elasticbeanstalk
    region: us-west-1 # Specify your region
    app: "docker"
    env: "DockerReactProject-env" # Copy it from Elastic Beanstalk dashboard
    bucket_name: "elasticbeanstalk-us-west-1-034275272121"
    bucket_path: "docker"
    on:
        branch: master
